package indi.nonoas.xbh.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import indi.nonoas.xbh.pojo.Account;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "ACCOUNT".
*/
public class AccountDao extends AbstractDao<Account, Long> {

    public static final String TABLENAME = "ACCOUNT";

    /**
     * Properties of entity Account.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property AccName = new Property(1, String.class, "accName", false, "ACC_NAME");
        public final static Property AccType = new Property(2, int.class, "accType", false, "ACC_TYPE");
        public final static Property InitBalance = new Property(3, String.class, "initBalance", false, "INIT_BALANCE");
        public final static Property IconId = new Property(4, int.class, "iconId", false, "ICON_ID");
        public final static Property IconUrl = new Property(5, String.class, "iconUrl", false, "ICON_URL");
    }


    public AccountDao(DaoConfig config) {
        super(config);
    }
    
    public AccountDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"ACCOUNT\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"ACC_NAME\" TEXT," + // 1: accName
                "\"ACC_TYPE\" INTEGER NOT NULL ," + // 2: accType
                "\"INIT_BALANCE\" TEXT," + // 3: initBalance
                "\"ICON_ID\" INTEGER NOT NULL ," + // 4: iconId
                "\"ICON_URL\" TEXT);"); // 5: iconUrl
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"ACCOUNT\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Account entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String accName = entity.getAccName();
        if (accName != null) {
            stmt.bindString(2, accName);
        }
        stmt.bindLong(3, entity.getAccType());
 
        String initBalance = entity.getInitBalance();
        if (initBalance != null) {
            stmt.bindString(4, initBalance);
        }
        stmt.bindLong(5, entity.getIconId());
 
        String iconUrl = entity.getIconUrl();
        if (iconUrl != null) {
            stmt.bindString(6, iconUrl);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Account entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String accName = entity.getAccName();
        if (accName != null) {
            stmt.bindString(2, accName);
        }
        stmt.bindLong(3, entity.getAccType());
 
        String initBalance = entity.getInitBalance();
        if (initBalance != null) {
            stmt.bindString(4, initBalance);
        }
        stmt.bindLong(5, entity.getIconId());
 
        String iconUrl = entity.getIconUrl();
        if (iconUrl != null) {
            stmt.bindString(6, iconUrl);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Account readEntity(Cursor cursor, int offset) {
        Account entity = new Account( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // accName
            cursor.getInt(offset + 2), // accType
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // initBalance
            cursor.getInt(offset + 4), // iconId
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5) // iconUrl
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Account entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setAccName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setAccType(cursor.getInt(offset + 2));
        entity.setInitBalance(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setIconId(cursor.getInt(offset + 4));
        entity.setIconUrl(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Account entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Account entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Account entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
