package indi.nonoas.xbh.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import indi.nonoas.xbh.pojo.AccBalance;
import indi.nonoas.xbh.pojo.Account;
import indi.nonoas.xbh.pojo.User;

import indi.nonoas.xbh.greendao.AccBalanceDao;
import indi.nonoas.xbh.greendao.AccountDao;
import indi.nonoas.xbh.greendao.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig accBalanceDaoConfig;
    private final DaoConfig accountDaoConfig;
    private final DaoConfig userDaoConfig;

    private final AccBalanceDao accBalanceDao;
    private final AccountDao accountDao;
    private final UserDao userDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        accBalanceDaoConfig = daoConfigMap.get(AccBalanceDao.class).clone();
        accBalanceDaoConfig.initIdentityScope(type);

        accountDaoConfig = daoConfigMap.get(AccountDao.class).clone();
        accountDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        accBalanceDao = new AccBalanceDao(accBalanceDaoConfig, this);
        accountDao = new AccountDao(accountDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(AccBalance.class, accBalanceDao);
        registerDao(Account.class, accountDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        accBalanceDaoConfig.clearIdentityScope();
        accountDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
    }

    public AccBalanceDao getAccBalanceDao() {
        return accBalanceDao;
    }

    public AccountDao getAccountDao() {
        return accountDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
